# Generated by Django 5.0.2 on 2024-02-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Admin', 'Admin'), ('IT', 'IT'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
